REM INSERTING into FILE_TYPES
SET DEFINE OFF;
Insert into FILE_TYPES (FILE_TYPE_ID,FILE_TYPE_NAME,FILE_TYPE_DESCRIPTION) values (1,'CSV-1','Comma seperated without enclosures.');
Insert into FILE_TYPES (FILE_TYPE_ID,FILE_TYPE_NAME,FILE_TYPE_DESCRIPTION) values (2,'CSV-2','Comma seperated with enclosures.');
Insert into FILE_TYPES (FILE_TYPE_ID,FILE_TYPE_NAME,FILE_TYPE_DESCRIPTION) values (3,'TXT-1','Fixed width without variable length records.');
Insert into FILE_TYPES (FILE_TYPE_ID,FILE_TYPE_NAME,FILE_TYPE_DESCRIPTION) values (4,'TXT-2','Fixed width with variable length records.');

REM INSERTING into FIXED_WIDTH_FILE_TYPES
SET DEFINE OFF;
Insert into FIXED_WIDTH_FILE_TYPES (FILE_TYPE_ID,FIXED_OR_VARIABLE_LENGTH,MIN_RECORD_LENGTH,MAX_RECORD_LENGTH) values (3,'F',50,50);
Insert into FIXED_WIDTH_FILE_TYPES (FILE_TYPE_ID,FIXED_OR_VARIABLE_LENGTH,MIN_RECORD_LENGTH,MAX_RECORD_LENGTH) values (4,'V',20,50);

REM INSERTING into DELIMITED_FILE_TYPES
SET DEFINE OFF;
Insert into DELIMITED_FILE_TYPES (FILE_TYPE_ID,DELIMITER,ENCLOSURE,PARSE_BY_DELIMITER,PARSE_BY_ENCLOSURE) values (1,',',null,'Y','N');
Insert into DELIMITED_FILE_TYPES (FILE_TYPE_ID,DELIMITER,ENCLOSURE,PARSE_BY_DELIMITER,PARSE_BY_ENCLOSURE) values (2,',','"','N','Y');


REM INSERTING into FILE_COLUMNS
SET DEFINE OFF;
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,1,'SERIES_REFERENCE','VARCHAR2',null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,2,'PRIOD','VARCHAR2',null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,3,'DATA_VALUE','NUMBER',null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,4,'SUPPRESSED','VARCHAR2',null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,5,'STATUS','VARCHAR2',null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,6,'UNITS',null,null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,7,'MAGNITUDE',null,null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,8,'SUBJECT',null,null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,9,'GROUP',null,null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,10,'SERIES_TITLE_1',null,null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,11,'SERIES_TITLE_2',null,null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,12,'SERIES_TITLE_3',null,null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,13,'SERIES_TITLE_4',null,null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,14,'SERIES_TITLE_5',null,null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,15,'RECORD_SEQUENCE',null,null,null,null);
Insert into FILE_COLUMNS (FILE_ID,COLUMN_SEQ,COLUMN_NAME,DATA_TYPE,DATA_FORMAT,COLUMN_TYPE,DEFAULT_VALUE) values (101,16,'CREATED_TIME',null,null,null,null);

REM INSERTING into HR.FILES
SET DEFINE OFF;
Insert into HR.FILES (FILE_ID,FILE_NAME,FILE_TYPE_ID,FIRST_COLUMN,HEADER_APPLICABLE,HEADER_IDENTIFIER_CHARS,TRAILER_APPLICABLE,TRAILER_IDENTIFIER_CHARS,FILE_DIRECTORY,EXT_TABLE,STAGE_TABLE,ERROR_TABLE) values (1,'EMPLOYMENT',1,'SERIES_REFERENCE','Y','Series_reference','Y','Total_records','EMPLOYMENT','EMPLOYMENT_EXT','EMPLOYMENT_STG',null);

commit;